name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to Dev
    uses: ./.github/workflows/reusable-deploy.yaml

    with:
      aws_region: ${{ vars.AWS_REGION }}
      ecr_repository: ${{ vars.AWS_REGION }}
      eks_cluster: ${{ vars.AWS_REGION }}

    secrets: inherit